### ISSUE TITLE
Feature idea: add a dedicated block for new releases

### ISSUE THREAD

**Issue by matks** [PrestaShop/core-weekly-generator#31]
Add a new feature into Core Weekly Generator to make it able to fetch GitHub releases for past week and write them.

This would create a block like this at the top:
```
## Releases

- PrestaShop 1.7.6.8
- Dashproducts module: v2.1.1
- ...
```

See https://build.prestashop.com/news/coreweekly-39-2020/ as an example

## Roadmap

If I am not wrong, here are the necessary steps to implement it:

- [ ] Introduce a class able to perform authenticated calls to GitHub API (because releases API require authentication)
- [ ] Use this class to crawl all PrestaShop organization repositories for their latest release
- [ ] Only keep the releases from target week
- [ ] Write the 'releases' Markdown part as above

Nice-to-have:
- [ ] Use a hardcoded mapping to be able to add "module" word in front of module repositories
- [ ] Some formatting (link to changelog ? detect whether it's minor, patch or major version) ?

**Comment by matks** [comment]
I looked at it, it seems https://developer.github.com/v3/search/ that we use does not provide releases search.

We could do it using the REST API from GitHub but it requires authentication.

**Comment by matks** [comment]
I did a PHP script using authenticated calls to obtain the releases data 😅 but I'll need something in python

https://github.com/matks/prestashop-repos-bulk-editor/blob/master/get-latest-releases.php

**Comment by matks** [comment]
I updated the issue description with a technical roadmap.

**Comment by PierreRambaud** [comment]
> I did a PHP script using authenticated calls to obtain the releases data  but I'll need something in python
> 
> https://github.com/matks/prestashop-repos-bulk-editor/blob/master/get-latest-releases.php

I can do it for you quickly if you want?

**Comment by matks** [comment]
@PierreRambaud I planned to do it as part of my learning process for Python 😁 but it feels fun to you, go ahead. I'll find other things to build in Python 😉

**Comment by matks** [comment]
Closed as this repository is about to be archived as a new [Core Generator](https://github.com/PrestaShop/presthubot/blob/master/src/App/Command/GitHubMonthlyReportCommand.php) has been constructed and this feature was added in the new generator.
